/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iniciodeseccion;

import iniciodeseccion.ConexionBD;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class RegistroFrame extends javax.swing.JFrame {

    private JTextField userField;
    private JPasswordField passField;
    private JTextField correoField;
    private JButton registerButton;
    
    public RegistroFrame() {
        //initComponents();
        
        setTitle("Registro de Usuario");
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        JPanel panel = new JPanel();
        add(panel);
        placeComponents (panel);
        
        registerButton.addActionListener(new ActionListener(){
            
            @Override
            
            public void actionPerformed(ActionEvent e) {
                
                String username = userField.getText();
                String password = new String(passField.getPassword());
                String correo = correoField.getText();
                registrarUsuario(username, password, correo);
                
            }
        });
    }
    
    private void placeComponents(JPanel panel) {
        
        panel.setLayout(null);
        
        JLabel userLabel = new JLabel("Usuario:");
        userLabel.setBounds(10, 20, 80, 25);
        panel.add(userLabel);
        
        userField = new JTextField(20);
        userField.setBounds(100, 20, 165, 25);
        panel.add(userField);
        
        passField = new JPasswordField(20);
        passField.setBounds(100, 50, 165, 25);
        panel.add(passField);
        
        JLabel correoLabel = new JLabel("Contraseña:");
        correoLabel.setBounds(10, 50, 80, 25);
        panel.add(correoLabel);
        
        correoField = new JTextField(20);
        correoField.setBounds(100, 20, 165, 25);
        panel.add(correoField);
        
        registerButton = new JButton("Registrar Usuario");
        registerButton.setBounds(10, 80, 150, 25);
        panel.add(registerButton);
        
    }
    
    private void registrarUsuario(String username, String password, String correo) {
        
        String sql = "INSERT INTO Usuarios (username, password, email) VALUES (?, ?, ?)"; //al registar usuarios con todos los componenetes de la tabla de la base de datos
        
        try (Connection conn = ConexionBD.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setString(1, username);
            stmt.setString(2, password);
            stmt.setString(3, correo);
            
            int rowsInserted = stmt.executeUpdate();
            
            if(rowsInserted > 0) {
                
                JOptionPane.showMessageDialog(null, "Registro Exitoso");
            }
                       
        }catch (SQLException e) {
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al registrar usuario");
        }
    }
    
    public static void main(String[] args) {
        
        SwingUtilities.invokeLater(new Runnable() {
            
            @Override
            
            public void run() {
                
                new RegistroFrame().setVisible(true); 
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
